name: Auto Deploy to EasyPanel

on:
  push:
    branches:
      - main  # Solo deploya cuando hagas push a main

jobs:
  deploy:
    runs-on: ubuntu-latest

    #agregamos un paso para hacer el deploy a EasyPanel
    steps:
      - name: Trigger EasyPanel Deploy
        run: |
          curl -X POST http://187.77.86.67:3000/api/deploy/bbf6ccf7636279fc2fcc54b240bd3dd582f466d6735c0bf7
